name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Enter sudo
      run: sudo echo "entering elevated privilage"
    - name: Run tests
      run: sudo /home/ubuntu/.cargo/bin/cargo test --verbose
